add bootstrap/some tests
DmitriyPodkovko/myfirstproject pull request #7
Opened 2020-12-22 20:54 UTC by DmitriyPodkovko

2021-01-02 08:01 UTC, Slawikus requested changes

2021-01-02 08:01 UTC, Slawikus commented on catalog/tests.py
> +        self.assertEqual(response.status_code, 200)
Этот пункт был уже проверен в предыдущем тесте - зачем его здесь прописывать ещё раз?

2021-01-02 08:01 UTC, Slawikus commented on catalog/tests.py
> +        response = self.client.get('/')
А для рутового пути (тот что просто /) нет имени пути?

2021-01-02 08:01 UTC, Slawikus commented on catalog/tests.py
> +    def test_signup_form(self):
Вот этот тест странный так как ты создаёшь юзера напрямую в базе данных и потом проверяешь есть он там или нет. Подозреваю что правильнее было бы создать юзера не сразу в базе, а через форму сайнапа (как ты делаешь во всех предыдущих тестах), и потом проверить есть ли пользователь с таким юзернеймом и мейлом в базе.

2021-01-02 08:01 UTC, Slawikus commented on catalog/tests.py
> +        response = self.client.get('/users/signup/')
А у пути сайнапа нет именного названия?

2021-01-02 08:01 UTC, Slawikus commented on catalog/tests.py
> +        self.assertEqual(get_user_model().objects.all()[0].username, self.username)
Вместо all()[0] можно просто first() написать, должно ж работать

2021-01-02 08:01 UTC, Slawikus commented on templates/category_add.html
> +    <p></p>
А это что за такой содержательный элемент?

2021-02-16 08:36 UTC, DmitriyPodkovko commented on catalog/tests.py
> +        response = self.client.get('/users/signup/')
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]
Мы сначала проверяем саму страницу /users/signup/  ,а потом ниже название signup

2021-02-16 08:37 UTC, DmitriyPodkovko commented on catalog/tests.py
> +    def test_signup_form(self):
Готово -работает, фух)

2021-02-21 18:16 UTC, Slawikus approved these changes

2021-02-22 20:10 UTC, merged