sort project by datecomment
DmitriyPodkovko/myfirstproject pull request #9
Opened 2021-04-22 17:51 UTC by DmitriyPodkovko

2021-04-24 10:02 UTC, Slawikus requested changes

2021-04-24 10:02 UTC, Slawikus commented on forum/models.py
> +        with connection.cursor() as cursor:
А что здесь за мистика происходит?

2021-04-24 10:02 UTC, Slawikus commented on catalog/models.py
> +    created_at_comment = models.DateTimeField(blank=True, null=True)
Ага, ты решил обновлять это поле после того как появляется новый комментарий, правильно?

2021-04-24 10:09 UTC, DmitriyPodkovko commented on catalog/models.py
> +    created_at_comment = models.DateTimeField(blank=True, null=True)
Да

2021-04-24 10:16 UTC, DmitriyPodkovko commented on forum/models.py
> +        with connection.cursor() as cursor:
С помощью connection и cursor мы имеем возможность обновлять главную таблицу Project, с нашим новым добавленным полем, с помощью выполнения UPDATE, после того как появился новый комментарий в любом Форуме проекта
 Конструкция: with connection.cursor() as cursor: 

 https://django.fun/docs/django/ru/3.1/topics/db/sql/

Использование курсора в качестве диспетчера контекста:
with connection.cursor() as c:
    c.execute(...)
эквивалентно:
c = connection.cursor()
try:
    c.execute(...)
finally:
    c.close()

2021-04-24 10:21 UTC, DmitriyPodkovko commented on forum/models.py
> +        with connection.cursor() as cursor:
Далее мы вытаскиваем id необходимого Проекта и подставляем в UPDATE id и дату создания комментария из Comment

2021-04-24 10:23 UTC, DmitriyPodkovko commented on forum/models.py
> +        with connection.cursor() as cursor:
и происходит обновление поля created_at_comment в Project
Работает быстро и легко

2021-04-24 11:26 UTC, Slawikus commented on forum/models.py
> +        with connection.cursor() as cursor:
А как ты вообще пришёл к идее использовать connection I cursor I raw sql query? В книге ж про это небыло ни слова. Оно ж здесь совершенно не нужно. Соединение с базой уже есть, Джанго его устанавливает. А апдейт поля можно сделать средствами Django ORM - сырые квери в базу совершенно не нужны.

2021-04-24 11:30 UTC, Slawikus commented on forum/models.py
> +        with connection.cursor() as cursor:
Можно просто что-то типа self.project.created_at_comment = self.created_at

2021-04-24 11:33 UTC, Slawikus commented on forum/models.py
> +            project_main = get_object_or_404(ProjectForum, id=self.project_forum.id)
А метод get object or 404 в моделях лучше вообще не использовать. Модель работает с базой данных - они ничего не знает и не должна знать о веб или хттп, а используя этот метод ты как раз притягиваешь веб в мир моделей

2021-04-25 15:56 UTC, Slawikus approved these changes

2021-04-25 17:30 UTC, merged